### ISSUE TITLE
[Svelte] export interface Input {} id missing the localized field

### ISSUE THREAD

**Issue by D-Marc1** [BuilderIO/builder#1844]
**Describe the bug**

I am using the Svelte SDK and the `Input` interface is missing the `localized` field. I am also using the latest version, **0.1.9**. The `localized` field exists on the `Input` interface on this GitHub repo, however.

**To Reproduce**
1. Download the Svelte Builder SDK
2. Check the `Input` interface and you'll see that the `localized` field is missing

**Comment by samijaber** [comment]
This should be fixed in the latest version `0.1.10`: https://unpkg.com/browse/@builder.io/sdk-svelte@0.1.10/package/types/input.d.ts

You can find `localized` in line 73.

Closing issue since it's fixed.

**Comment by D-Marc1** [comment]
@samijaber, I believe this should be reopened, as I'm still getting a type error that localized doesn't exist on type `Input`. Interestingly, according to the unpkg.com link, it looks like this was added many versions before. However I still still an error in my code.

I used: `import type { RegisteredComponent } from '@builder.io/sdk-svelte`

**Comment by samijaber** [comment]
Thanks for flagging this issue again. I took a deeper look: we accidentally have the `Input` type duplicated, that's why!

https://github.com/BuilderIO/builder/blob/0eed8b38448cf78fdc4a824cb3a6089dbc1d16be/packages/sdks/src/types/input.ts#L1

https://github.com/BuilderIO/builder/blob/0eed8b38448cf78fdc4a824cb3a6089dbc1d16be/packages/sdks/src/types/components.ts#L3

We need to combine them into 1, and make sure it includes all of the types from both.

Thanks again for pointing out this was not fixed!
